<?xml version="1.0" encoding="utf-8"?><Database Name="Restaurant" Class="ContextoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Restaurant;Integrated Security=True" SettingsObjectName="DATOS.My.MySettings" SettingsPropertyName="RestaurantConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mesas" Member="Mesas">
    <Type Name="Mesa">
      <Column Name="ID_MESA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CAPACIDAD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ORDENES" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ID_MESONERO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="ID_PLATO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TIPO" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Caja" Member="Cajas">
    <Type Name="Caja">
      <Column Name="ID_FACTURA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_MESA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PRODUCTO" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CANTIDAD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PRECIO" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleado">
      <Column Name="ID_CTR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EMPLEADO" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="ID_DPTO" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EDAD" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Deposito" Member="Depositos">
    <Type Name="Deposito">
      <Column Name="ID_CTR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PRODUCTO" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="CANTIDAD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="ID_USER" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PASS" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO_USER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>